#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage:  ./_patch.softclip_exclude-rdBP.sh  intraBP_addCnt.list"; 
  echo "        exclude redundant SV-BreakPoint from [intraBP.list] which generated by mal-alignment on singlet repeat";
  exit 1;
fi

tarfile=$1
awk -F"\t" '{print $3,$5 FS $1,$7 FS $9  FS  $13":"$14":"$15":"$16":"$17":"$18 FS $0}' ${tarfile} | sort > .all_list
cut -f1-4 .all_list | uniq -c | awk '$1!=1{print}' | cut -c9- > .rd_list
echo -n "" > .nrd_list

N=1
while read buff
do
   sed -n ${N}p .rd_list | fgrep -f - .all_list | cut -f5- | sort -k8,8nr -t$'\t' | head -n1 >> .nrd_list
   N=$(($N+1))
done < ./.rd_list

fgrep -f .rd_list -v .all_list | cut -f5- > ${tarfile}_0
cat .nrd_list ${tarfile}_0 | sort -k8,8nr -t$'\t' > ${tarfile}

rm .all_list .rd_list .nrd_list;
