rm  ./all.sam.cla.ff.ins51
rm  ./all.sam.cla.ff.ins51.err
rm  ./all.sam.cla.ff.ins51.rmMulti2
rm  ./all.sam.cla.ff.ins51.rmMulti2.err
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.err
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2.rmDup.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.stderr
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.stderr
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.stderr
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.bam
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.cla.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.1
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.err
rm  ./all.sam.cla.fr_n.rmMulti2
rm  ./all.sam.cla.fr_n.rmMulti2.err
rm  ./all.sam.cla.fr_n.rmMulti2.sco37
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.err
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup.err
rm  ./all.sam.cla.rf.ins
rm  ./all.sam.cla.rf.ins.err
rm  ./all.sam.cla.rf.ins.rmMulti2
rm  ./all.sam.cla.rf.ins.rmMulti2.err
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.err
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2.rmDup.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam.stderr
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam.sort.bam
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam.sort.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu.rm
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu.rm.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu.rm
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu.rm.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.cla.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.1
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.err
rm  ./all.sam.cla.rr.ins51
rm  ./all.sam.cla.rr.ins51.err
rm  ./all.sam.cla.rr.ins51.rmMulti2
rm  ./all.sam.cla.rr.ins51.rmMulti2.err
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.err
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.mis2
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.stderr
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.stderr
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam.sort.bam
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam.sort.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.cla.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.1
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff

rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.chk
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.chk.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.rm.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.rm.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.rm.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.chk
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.chk.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.rm.err
rm  ./all.sam.cla.tr.rmMulti2
rm  ./all.sam.cla.tr.rmMulti2.err
rm  ./all.sam.cla.tr.rmMulti2.sco37
rm  ./all.sam.cla.tr.rmMulti2.sco37.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p1.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p2.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p3.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p4.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.rmDup
rm  ./deletion2_sco37.full.r2.all.noL.cluster.insMax.read4up.txt
rm  ./deletion2_sco37.full.r2.all.noL.cluster.insMax.txt
rm  ./deletion2_sco37.full.r2.all.noL.cluster.insMax.txt.sort1
rm  ./deletion2_sco37.full.r2.all.noL.cluster.txt
rm  ./deletion2_sco37.full.r2.all.noL.cluster.txt.1
rm  ./deletion2_sco37.full.r2.all.noL.cluster.txt.1.sort10
rm  ./deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4
rm  ./deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1
rm  ./deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1
rm  ./deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1.sort10
rm  ./deletion2_sco37.full.r2.all.noL.txt
rm  ./deletion2_sco37.full.r2.all.txt
rm  ./deletion2_sco37.full.r2.txt
rm  ./deletion2_sco37.full_fr.r2.txt.2
rm  ./deletion2_sco37.full_fr.r2.txt.3
rm  ./deletion2_sco37.full_fr.r2.txt.4
rm  ./deletion2_sco37.full_fr.r2.txt.5
rm  ./deletion2_sco37.full_fr.r2.txt.6
rm  ./deletion2_sco37.full_fr.r2_r1.txt.4
rm  ./deletion2_sco37.mis2
# rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.cluster.txt
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort1
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort10
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt.sort1
rm  ./deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt.sort10
rm  ./deletion2new_sco37.r3.noL.insMax.e+3.rmMulti.rmNoPrefect.txt
rm  ./deletion3new_1.txt
rm  ./deletion3new_circos.txt
rm  ./deletion3new_sco37.txt
rm  ./deletion_fr
rm  ./deletion_fr.0
rm  ./deletion_fr.1
rm  ./deletion_fr.2
rm  ./deletion_fr.3
rm  ./deletion_fr.4
rm  ./deletion_fr.5
rm  ./deletion_fr.6
rm  ./deletion_new.txt
rm  ./deletion_new_dis1000_sort1.txt
rm  ./deletion_new_dis1000_sort10.txt
rm  ./deletion_new_fr_gene4.txt
rm  ./deletion_new_fr_gene4.txt.sort1
rm  ./deletion_new_fr_gene4.txt.sort10
rm  ./deletion_new_fr_gene5.txt.sort1
rm  ./deletion_new_fr_gene6.txt.sort1
rm  ./deletion_new_fr_gene_all.txt
rm  ./deletion_new_fr_gene_all.txt.sort1
rm  ./deletion_new_fr_gene_all.txt.sort10
rm  ./deletion_new_sort1.txt
rm  ./deletion_new_sort10.txt
rm  ./fusion10new_gene.txt
rm  ./fusion10new_gene_inframe.txt
rm  ./fusion10new_gene_inframe.txt.2
rm  ./fusion5new_gene.txt
rm  ./fusion6new_gene.txt
rm  ./fusion7new_gene.txt
rm  ./fusion9new_gene.txt
rm  ./fusion9new_gene_inframe.txt
rm  ./inversion-ff_new_sort1.txt
rm  ./inversion-ff_new_sort1.txt.1
rm  ./inversion-ff_new_sort10.txt
rm  ./inversion-rr_new_sort1.txt
rm  ./inversion-rr_new_sort1.txt.1
rm  ./inversion-rr_new_sort10.txt
rm  ./inversion2_ff_sco37.full.r2.all.noL.cluster.read4up.txt
rm  ./inversion2_ff_sco37.full.r2.all.noL.cluster.txt
rm  ./inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1
rm  ./inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1.sort1
rm  ./inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1.sort10
rm  ./inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4
rm  ./inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1
rm  ./inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1
rm  ./inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1.sort10
rm  ./inversion2_rr_sco37.full.r2.all.noL.cluster.read4up.txt
rm  ./inversion2_rr_sco37.full.r2.all.noL.cluster.txt
rm  ./inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1
rm  ./inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1.sort1
rm  ./inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1.sort10
rm  ./inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4
rm  ./inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1
rm  ./inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1
rm  ./inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1.sort10
rm  ./inversion2_sco37.full.r2.all.noL.txt
rm  ./inversion2_sco37.full.r2.all.txt
rm  ./inversion2_sco37.full_ff.r2.txt
rm  ./inversion2_sco37.full_ff.r2.txt.2
rm  ./inversion2_sco37.full_ff.r2.txt.3
rm  ./inversion2_sco37.full_ff.r2.txt.4
rm  ./inversion2_sco37.full_ff.r2.txt.5
rm  ./inversion2_sco37.full_ff.r2.txt.6
rm  ./inversion2_sco37.full_ff.r2_r1.txt.4
rm  ./inversion2_sco37.full_rr.r2.txt
rm  ./inversion2_sco37.full_rr.r2.txt.2
rm  ./inversion2_sco37.full_rr.r2.txt.3
rm  ./inversion2_sco37.full_rr.r2.txt.4
rm  ./inversion2_sco37.full_rr.r2.txt.5
rm  ./inversion2_sco37.full_rr.r2.txt.6
rm  ./inversion2_sco37.full_rr.r2_r1.txt.4
rm  ./inversion2_sco37.mis2_ff
rm  ./inversion2_sco37.mis2_rr
# rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort1
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort10
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort1
rm  ./inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort10
rm  ./inversion2new_ff_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt
# rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort1
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort10
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort1
rm  ./inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort10
rm  ./inversion2new_rr_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt
rm  ./inversion3new_sco37_ff.txt
rm  ./inversion3new_sco37_rr.txt
rm  ./inversion_ff
rm  ./inversion_ff.0
rm  ./inversion_ff.1
rm  ./inversion_ff.2
rm  ./inversion_ff.3
rm  ./inversion_ff.4
rm  ./inversion_ff.5
rm  ./inversion_ff.6
rm  ./inversion_new.txt
rm  ./inversion_new_ff_gene4.txt
rm  ./inversion_new_ff_gene4.txt.sort1
rm  ./inversion_new_ff_gene4.txt.sort10
rm  ./inversion_new_ff_gene5.txt.sort1
rm  ./inversion_new_ff_gene6.txt.sort1
rm  ./inversion_new_rr_gene4.txt
rm  ./inversion_new_rr_gene4.txt.sort1
rm  ./inversion_new_rr_gene4.txt.sort10
rm  ./inversion_new_rr_gene5.txt.sort1
rm  ./inversion_new_rr_gene6.txt.sort1
rm  ./inversion_rr
rm  ./inversion_rr.0
rm  ./inversion_rr.1
rm  ./inversion_rr.2
rm  ./inversion_rr.3
rm  ./inversion_rr.4
rm  ./inversion_rr.5
rm  ./inversion_rr.6
rm  ./rearrangement10new_gene.txt
rm  ./rearrangement5new.txt
rm  ./rearrangement5new_gene.txt
rm  ./rearrangement6new.txt
rm  ./rearrangement6new_gene.txt
rm  ./rearrangement7new.txt
rm  ./rearrangement7new.txt.1
rm  ./rearrangement7new_gene.txt
rm  ./rearrangement8new.txt
rm  ./rearrangement9new.txt
rm  ./rearrangement9new_gene.txt
rm  ./rearrangement_new.txt
rm  ./rearrangement_new.txt.2
rm  ./tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.read4up.txt
rm  ./tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt
rm  ./tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt.sort1
rm  ./tandem_duplication2_sco37.full.r2.all.noL.cluster.txt
rm  ./tandem_duplication2_sco37.full.r2.all.noL.cluster.txt.1
rm  ./tandem_duplication2_sco37.full.r2.all.noL.cluster.txt.1.sort10
rm  ./tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4
rm  ./tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1
rm  ./tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1.1
rm  ./tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1.1.sort10
rm  ./tandem_duplication2_sco37.full.r2.all.noL.txt
rm  ./tandem_duplication2_sco37.full.r2.all.txt
rm  ./tandem_duplication2_sco37.full_rf.r2.txt
rm  ./tandem_duplication2_sco37.full_rf.r2.txt.2
rm  ./tandem_duplication2_sco37.full_rf.r2.txt.3
rm  ./tandem_duplication2_sco37.full_rf.r2.txt.4
rm  ./tandem_duplication2_sco37.full_rf.r2.txt.5
rm  ./tandem_duplication2_sco37.full_rf.r2.txt.6
rm  ./tandem_duplication2_sco37.full_rf.r2_r1.txt.4
rm  ./tandem_duplication2_sco37.mis2_rf
# rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.cluster.txt
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort1
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort10
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt.sort1
rm  ./tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt.sort10
rm  ./tandem_duplication2new_sco37.r3.noL.ins100up.e+3.rmMulti.rmNoPrefect.txt
rm  ./tandem_duplication3new_sco37.txt
rm  ./tandem_duplication_new_sort1.txt
rm  ./tandem_duplication_new_sort10.txt
rm  ./tandem_new.txt
rm  ./tandem_new_rf_gene4.txt
rm  ./tandem_new_rf_gene4.txt.sort1
rm  ./tandem_new_rf_gene4.txt.sort10
rm  ./tandem_new_rf_gene5.txt.sort1
rm  ./tandem_new_rf_gene6.txt.sort1
rm  ./tandem_rf
rm  ./tandem_rf.0
rm  ./tandem_rf.1
rm  ./tandem_rf.2
rm  ./tandem_rf.3
rm  ./tandem_rf.4
rm  ./tandem_rf.5
rm  ./tandem_rf.6
rm  ./translocation-ff_new_sort1.txt
rm  ./translocation-ff_new_sort1.txt.1
rm  ./translocation-ff_new_sort10.txt
rm  ./translocation-fr_new_sort1.txt
rm  ./translocation-fr_new_sort1.txt.1
rm  ./translocation-fr_new_sort10.txt
rm  ./translocation-rr_new_sort1.txt
rm  ./translocation-rr_new_sort1.txt.1
rm  ./translocation-rr_new_sort10.txt
rm  ./translocation2_ff_sco37.full.r2.all.noL.cluster.read4up.txt
rm  ./translocation2_ff_sco37.full.r2.all.noL.cluster.txt
rm  ./translocation2_ff_sco37.full.r2.all.noL.cluster.txt.1
rm  ./translocation2_ff_sco37.full.r2.all.noL.cluster.txt.1.sort1
# rm  ./translocation2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4
# rm  ./translocation2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1
rm  ./translocation2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1
rm  ./translocation2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1.sort10
rm  ./translocation2_fr_sco37.full.r2.all.noL.cluster.read4up.txt
rm  ./translocation2_fr_sco37.full.r2.all.noL.cluster.txt
rm  ./translocation2_fr_sco37.full.r2.all.noL.cluster.txt.1
rm  ./translocation2_fr_sco37.full.r2.all.noL.cluster.txt.1.sort1
rm  ./translocation2_fr_sco37.full.r2.all.noL.read4up.cluster.txt.read4
# rm  ./translocation2_fr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.fr.e-1
rm  ./translocation2_fr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1
rm  ./translocation2_fr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1.sort10
rm  ./translocation2_rr_sco37.full.r2.all.noL.cluster.read4up.txt
rm  ./translocation2_rr_sco37.full.r2.all.noL.cluster.txt
rm  ./translocation2_rr_sco37.full.r2.all.noL.cluster.txt.1
rm  ./translocation2_rr_sco37.full.r2.all.noL.cluster.txt.1.sort1
rm  ./translocation2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4
# rm  ./translocation2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1
rm  ./translocation2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1
rm  ./translocation2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1.sort10
rm  ./translocation2_sco37.full.r2.all.noL.txt
rm  ./translocation2_sco37.full.r2.all.txt
rm  ./translocation2_sco37.full_ff.r2.txt
rm  ./translocation2_sco37.full_ff.r2.txt.2
rm  ./translocation2_sco37.full_ff.r2.txt.3
rm  ./translocation2_sco37.full_ff.r2.txt.4
rm  ./translocation2_sco37.full_ff.r2.txt.5
rm  ./translocation2_sco37.full_ff.r2.txt.6
rm  ./translocation2_sco37.full_ff.r2_r1.txt.4
rm  ./translocation2_sco37.full_fr.r2.txt
rm  ./translocation2_sco37.full_fr.r2.txt.2
rm  ./translocation2_sco37.full_fr.r2.txt.3
rm  ./translocation2_sco37.full_fr.r2.txt.4
rm  ./translocation2_sco37.full_fr.r2.txt.5
rm  ./translocation2_sco37.full_fr.r2.txt.6
rm  ./translocation2_sco37.full_fr.r2_r1.txt.4
rm  ./translocation2_sco37.full_rr.r2.txt
rm  ./translocation2_sco37.full_rr.r2.txt.2
rm  ./translocation2_sco37.full_rr.r2.txt.3
rm  ./translocation2_sco37.full_rr.r2.txt.4
rm  ./translocation2_sco37.full_rr.r2.txt.5
rm  ./translocation2_sco37.full_rr.r2.txt.6
rm  ./translocation2_sco37.full_rr.r2_r1.txt.4
rm  ./translocation2_sco37.mis2_ff
rm  ./translocation2_sco37.mis2_fr
rm  ./translocation2_sco37.mis2_rr
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort1
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort10
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort1
rm  ./translocation2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort10
rm  ./translocation2new_ff_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort1
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort10
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.txt
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort1
rm  ./translocation2new_fr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort10
rm  ./translocation2new_fr_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort1
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new.sort10
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort1
rm  ./translocation2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort10
rm  ./translocation2new_rr_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt
rm  ./translocation3new_sco37_ff.txt
rm  ./translocation3new_sco37_fr.txt
rm  ./translocation3new_sco37_rr.txt
rm  ./translocation_ff
rm  ./translocation_ff.0
rm  ./translocation_ff.1
rm  ./translocation_ff.2
rm  ./translocation_ff.3
rm  ./translocation_ff.4
rm  ./translocation_ff.5
rm  ./translocation_ff.6
rm  ./translocation_fr
rm  ./translocation_fr.0
rm  ./translocation_fr.1
rm  ./translocation_fr.2
rm  ./translocation_fr.3
rm  ./translocation_fr.4
rm  ./translocation_fr.5
rm  ./translocation_fr.6
rm  ./translocation_new.txt
rm  ./translocation_new_ff_gene4.txt
rm  ./translocation_new_ff_gene4.txt.sort1
rm  ./translocation_new_ff_gene4.txt.sort10
rm  ./translocation_new_ff_gene5.txt.sort1
rm  ./translocation_new_ff_gene6.txt.sort1
rm  ./translocation_new_fr_gene4.txt
rm  ./translocation_new_fr_gene4.txt.sort1
rm  ./translocation_new_fr_gene4.txt.sort10
rm  ./translocation_new_fr_gene5.txt.sort1
rm  ./translocation_new_fr_gene6.txt.sort1
rm  ./translocation_new_rr_gene4.txt
rm  ./translocation_new_rr_gene4.txt.sort1
rm  ./translocation_new_rr_gene4.txt.sort10
rm  ./translocation_new_rr_gene5.txt.sort1
rm  ./translocation_new_rr_gene6.txt.sort1
rm  ./translocation_rr
rm  ./translocation_rr.0
rm  ./translocation_rr.1
rm  ./translocation_rr.2
rm  ./translocation_rr.3
rm  ./translocation_rr.4
rm  ./translocation_rr.5
rm  ./translocation_rr.6
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu; fi
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.srt ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.srt; fi
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu; fi
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.srt ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.srt; fi
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu; fi
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.srt ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.srt; fi
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.srt ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.srt; fi
if [ -e ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu ]; then  rm ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu; fi
