rm  ./all.sam.cla.ff.ins51.err
rm  ./all.sam.cla.ff.ins51
rm  ./all.sam.cla.ff.ins51.rmMulti2.err
rm  ./all.sam.cla.ff.ins51.rmMulti2
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.err
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2.rmDup.err
rm  ./all.sam.cla.ff.ins51.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.stderr
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.stderr
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.bam
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.err
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.out
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.stderr
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.bam
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.cla.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.1
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.err
rm  ./all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort
rm  ./all.sam.cla.fr_n.rmMulti2.err
rm  ./all.sam.cla.fr_n.rmMulti2
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.err
rm  ./all.sam.cla.fr_n.rmMulti2.sco37
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup.err
rm  ./all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.rf.ins.err
rm  ./all.sam.cla.rf.ins
rm  ./all.sam.cla.rf.ins.rmMulti2.err
rm  ./all.sam.cla.rf.ins.rmMulti2
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.err
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2.rmDup.err
rm  ./all.sam.cla.rf.ins.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam.stderr
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam.sort.bam
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.bam.sort.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu.rm.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+.clu.rm
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.+
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu.rm.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-.clu.rm
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.-
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.cla.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.1
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.err
rm  ./all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort
rm  ./all.sam.cla.rr.ins51.err
rm  ./all.sam.cla.rr.ins51
rm  ./all.sam.cla.rr.ins51.rmMulti2.err
rm  ./all.sam.cla.rr.ins51.rmMulti2
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.err
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.mis2
rm  ./all.sam.cla.rr.ins51.rmMulti2.sco37.mis2.rmDup
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.chk
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.2
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.-.sort.clu.min2
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.stderr
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.bam.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.clu
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.+.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.stderr
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.bam
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.bam.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.clu
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.err
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.-.sort.out
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam.sort.bam
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.bam.sort.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.cla.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.1
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.clu.min2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.srt
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.chk.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.chk
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.min2.i2.rmDup
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.rm.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.ff
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.srt
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.rm.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr+
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.srt
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.rm.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.fr-
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu
rm  ./.tmp_all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.srt
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.chk.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.chk
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.size.1
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup.2.size
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.min2.i2.rmDup
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.rm.err
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr.clu.rm
rm  ./all.sam.cla.tr.rmDup.rmMulti2.sco37.mis2.sort.rr
rm  ./all.sam.cla.tr.rmMulti2.err
rm  ./all.sam.cla.tr.rmMulti2
rm  ./all.sam.cla.tr.rmMulti2.sco37.err
rm  ./all.sam.cla.tr.rmMulti2.sco37
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p1.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p2.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p3.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.p4.rmDup.err
rm  ./all.sam.cla.tr.rmMulti2.sco37.mis2.rmDup
rm  ./deletion2_sco37.full.r2.txt
rm  ./deletion2_sco37.mis2
rm  ./deletion_fr
rm  ./deletion_fr.0
rm  ./deletion_fr.1
rm  ./deletion_fr.2
rm  ./deletion_fr.3
rm  ./deletion_fr.4
rm  ./deletion_fr.5
rm  ./deletion_fr.6
rm  ./inversion2_sco37.full_ff.r2.txt
rm  ./inversion2_sco37.full_rr.r2.txt
rm  ./inversion2_sco37.mis2_ff
rm  ./inversion2_sco37.mis2_rr
rm  ./inversion_ff
rm  ./inversion_ff.0
rm  ./inversion_ff.1
rm  ./inversion_ff.2
rm  ./inversion_ff.3
rm  ./inversion_ff.4
rm  ./inversion_ff.5
rm  ./inversion_ff.6
rm  ./inversion_rr
rm  ./inversion_rr.0
rm  ./inversion_rr.1
rm  ./inversion_rr.2
rm  ./inversion_rr.3
rm  ./inversion_rr.4
rm  ./inversion_rr.5
rm  ./inversion_rr.6
rm  ./tandem_duplication2_sco37.full_rf.r2.txt
rm  ./tandem_duplication2_sco37.mis2_rf
rm  ./tandem_rf
rm  ./tandem_rf.0
rm  ./tandem_rf.1
rm  ./tandem_rf.2
rm  ./tandem_rf.3
rm  ./tandem_rf.4
rm  ./tandem_rf.5
rm  ./tandem_rf.6
rm  ./translocation2_sco37.full_ff.r2.txt
rm  ./translocation2_sco37.full_fr.r2.txt
rm  ./translocation2_sco37.full_rr.r2.txt
rm  ./translocation2_sco37.mis2_ff
rm  ./translocation2_sco37.mis2_fr
rm  ./translocation2_sco37.mis2_rr
rm  ./translocation_ff
rm  ./translocation_ff.0
rm  ./translocation_ff.1
rm  ./translocation_ff.2
rm  ./translocation_ff.3
rm  ./translocation_ff.4
rm  ./translocation_ff.5
rm  ./translocation_ff.6
rm  ./translocation_fr
rm  ./translocation_fr.0
rm  ./translocation_fr.1
rm  ./translocation_fr.2
rm  ./translocation_fr.3
rm  ./translocation_fr.4
rm  ./translocation_fr.5
rm  ./translocation_fr.6
rm  ./translocation_rr
rm  ./translocation_rr.0
rm  ./translocation_rr.1
rm  ./translocation_rr.2
rm  ./translocation_rr.3
rm  ./translocation_rr.4
rm  ./translocation_rr.5
rm  ./translocation_rr.6
