#!/bin/sh
#$ -S /bin/sh
#$ -m ea
#$ -cwd 

if [ $# -lt 2 ]; then
  echo "usage: com.rearrangement.2.fr.pbs [max insert length(bp)] [file.conf] (Log_file)" 1>&2
  exit 1
fi

MAX_INSERT=$1
. $2
LOG=$3
JID=void

WDIR=`pwd | rev | cut -d '/' -f1 | rev`

if [ ! -s "./all.sam.cla.fr_n" ];then
# cat ./*.sam*.cla.fr_n > .fr_n; mv .fr_n all.sam.cla.fr_n
  cat ./*.sam*.cla.fr_n > .fr_n;  rm ./*.sam*.cla.fr_n;  mv .fr_n all.sam.cla.fr_n
fi

$RSC/extractMultiHit2_mem.pl all.sam.cla.fr_n 1> all.sam.cla.fr_n.rmMulti2 2> all.sam.cla.fr_n.rmMulti2.err
ls -l all.sam.cla.fr_n.rmMulti2 | awk -v wd=${WDIR}"_stp2fr-1/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractHighMapSco_bwa.pl all.sam.cla.fr_n.rmMulti2 $MAPQ 1> all.sam.cla.fr_n.rmMulti2.sco37 2> all.sam.cla.fr_n.rmMulti2.sco37.err
ls -l all.sam.cla.fr_n.rmMulti2.sco37 | awk -v wd=${WDIR}"_stp2fr-2/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractHighQualityAlignment.pl all.sam.cla.fr_n.rmMulti2.sco37 4 1> all.sam.cla.fr_n.rmMulti2.sco37.mis2 2> all.sam.cla.fr_n.rmMulti2.sco37.mis2.err
ls -l all.sam.cla.fr_n.rmMulti2.sco37.mis2 | awk -v wd=${WDIR}"_stp2fr-3/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/rmPCRDupFrSam_new_2.pl all.sam.cla.fr_n.rmMulti2.sco37.mis2 1> all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup 2> all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup.err
ls -l all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup | awk -v wd=${WDIR}"_stp2fr-4/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG


#---patch.for${REF_FAI}_221227---

awk -F"\t" '{gsub("chr","",$3); gsub("chr","",$7); for(i=1;i<NF;i++)printf $i"\t"; print $NF}' all.sam.cla.fr_n.rmMulti2.sco37.mis2.rmDup > all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2

$SAMTOOLS_DIR/samtools view -bt $REF_FAI -o all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.stderr
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam | awk -v wd=${WDIR}"_stp2fr-5/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$SAMTOOLS_DIR/samtools sort all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam -o all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.bam 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.err
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.bam | awk -v wd=${WDIR}"_stp2fr-6/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$SAMTOOLS_DIR/samtools view -o all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.bam.sort.bam 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.err
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort | awk -v wd=${WDIR}"_stp2fr-7/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

awk -F"\t" '{$3="chr"$3; if($7!="=")$7="chr"$7; for(i=1;i<NF;i++)printf $i"\t"; print $NF}' all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort > .all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort  &&  mv .all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort

#---

$RSC/classifyFR.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.cla.err
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+ | awk -v wd=${WDIR}"_stp2fr-8/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster2_bwa_new2.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+ exCl_length 2 $MAPQ 1> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu.err
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu | awk -v wd=${WDIR}"_stp2fr-9/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster2_bwa_new2.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.- exCl_length 2 $MAPQ 1> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu.err
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu | awk -v wd=${WDIR}"_stp2fr-10/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG


$RSC/extractBothCluster_3_bwa.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.+.clu all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.-.clu 4 1> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.err
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2 | awk -v wd=${WDIR}"_stp2fr-11/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractBothCluster2_bwa.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2 2 > all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2 | awk -v wd=${WDIR}"_stp2fr-12/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/chkCluster.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2 2 exCl_length 1> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk.err
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk | awk -v wd=${WDIR}"_stp2fr-12.5/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

# $RSC/rmLargeCluster2_bwa_new.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2 $MAX_INSERT 1> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.err
# $RSC/rmLargeCluster2_bwa_new.pl all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk $MAX_INSERT 1> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size 2> all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size.err
cp  all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.chk  all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size
ls -l all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size | awk -v wd=${WDIR}"_stp2fr-13/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

#---
# flg=0
# for err_file in `cat $DGR/list/.cr2_fr.err.list`
# do
#   if [ -s $err_file ]; then flg=1; fi
# done
# 
# if [ $flg -eq 1 ]; then 
#   echo "WARNING:  error message generated in com.rearrangement.2.fr, as follows:"
#   for err_file in `cat $DGR/list/.cr2_fr.err.list`
#   do 
#     if [ -s $err_file ]; then 
#       echo " -> "$err_file
#       cat $err_file
#     else
#       rm $err_file
#     fi
#   done
# #else 
# #  awk '{print "rm "$1}' $DGR/list/.cr2_fr.err.list > ._fr; sh ._fr
# #  rm ._fr 
# fi
