#!/bin/sh
#$ -S /bin/sh
#$ -m ea
#$ -cwd

if [ $# -lt 2 ]; then
  echo "usage: com.rearrangement.4.inversion.pbs [max insert length(bp)] [file.conf] (Log_file)" 1>&2
  exit 1
fi

MAX_INSERT=$1
. $2
LOG=$3
JID=void

WDIR=`pwd | rev | cut -d '/' -f1 | rev`


$RSC/chkOverlapCluster_new.pl ../normal/inversion2_sco37.full_ff.r2.txt inversion2_sco37.full_ff.r2.txt $READ_LEN_N $READ_LEN > inversion2_sco37.full_ff.r2.txt.2
ls -l inversion2_sco37.full_ff.r2.txt.2 | awk -v wd=${WDIR}"_stp4inv-1/20" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG
$RSC/viewClusterRegion.pl inversion2_sco37.full_ff.r2.txt.2 > inversion2_sco37.full_ff.r2.txt.3
$RSC/viewClusterRegion2.pl inversion2_sco37.full_ff.r2.txt.3 $READ_LEN > inversion2_sco37.full_ff.r2.txt.4
$RSC/viewClusterRegion.pl inversion2_sco37.full_ff.r2.txt > inversion2_sco37.full_ff.r2.txt.5
$RSC/viewClusterRegion2.pl inversion2_sco37.full_ff.r2.txt.5 $READ_LEN > inversion2_sco37.full_ff.r2.txt.6

$RSC/chkOverlapCluster_new.pl ../normal/inversion2_sco37.full_rr.r2.txt inversion2_sco37.full_rr.r2.txt $READ_LEN_N $READ_LEN > inversion2_sco37.full_rr.r2.txt.2
ls -l inversion2_sco37.full_rr.r2.txt.2 | awk -v wd=${WDIR}"_stp4inv-2/20" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG
$RSC/viewClusterRegion.pl inversion2_sco37.full_rr.r2.txt.2 > inversion2_sco37.full_rr.r2.txt.3
$RSC/viewClusterRegion2.pl inversion2_sco37.full_rr.r2.txt.3 $READ_LEN > inversion2_sco37.full_rr.r2.txt.4
$RSC/viewClusterRegion.pl inversion2_sco37.full_rr.r2.txt > inversion2_sco37.full_rr.r2.txt.5
$RSC/viewClusterRegion2.pl inversion2_sco37.full_rr.r2.txt.5 $READ_LEN > inversion2_sco37.full_rr.r2.txt.6

cat inversion2_sco37.full_??.r2.txt.6 > inversion2_sco37.full.r2.all.txt
cat inversion2_sco37.full_??.r2.txt.4 > inversion2_sco37.full.r2.all.noL.txt
CNT=`wc -l inversion2_sco37.full.r2.all.txt | cut -d" " -f1`
ls -l inversion2_sco37.full.r2.all.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-3/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`wc -l inversion2_sco37.full.r2.all.noL.txt | cut -d" " -f1`
ls -l inversion2_sco37.full.r2.all.noL.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-4/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractNoL_ff.pl ../normal/all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51 inversion2_sco37.full_ff.r2.txt.4 $READ_LEN > inversion2_sco37.full_ff.r2_r1.txt.4
$RSC/extractNoL_rr.pl ../normal/all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51 inversion2_sco37.full_rr.r2.txt.4 $READ_LEN > inversion2_sco37.full_rr.r2_r1.txt.4
CNT=`wc -l inversion2_sco37.full_ff.r2_r1.txt.4 | cut -d" " -f1`
ls -l inversion2_sco37.full_ff.r2_r1.txt.4 | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-5/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`wc -l inversion2_sco37.full_rr.r2_r1.txt.4 | cut -d" " -f1`
ls -l inversion2_sco37.full_rr.r2_r1.txt.4 | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-6/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster4.pl inversion2_sco37.full_ff.r2_r1.txt.4 all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size $READ_LEN > inversion2_ff_sco37.full.r2.all.noL.cluster.txt
$RSC/extractCluster4.pl inversion2_sco37.full_rr.r2_r1.txt.4 all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size $READ_LEN > inversion2_rr_sco37.full.r2.all.noL.cluster.txt
CNT=`grep -c "^#####" inversion2_ff_sco37.full.r2.all.noL.cluster.txt`
ls -l inversion2_ff_sco37.full.r2.all.noL.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-7/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`grep -c "^#####" inversion2_rr_sco37.full.r2.all.noL.cluster.txt`
ls -l inversion2_rr_sco37.full.r2.all.noL.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-8/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl inversion2_ff_sco37.full.r2.all.noL.cluster.txt $READ_LEN > inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1
sort -k 10,10nr inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1 > inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1.sort10
sort -k 1,1nr inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1 > inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1.sort1
$RSC/extract2.pl inversion2_ff_sco37.full.r2.all.noL.cluster.txt.1.sort1 0 4 > inversion2_ff_sco37.full.r2.all.noL.cluster.read4up.txt
CNT=`wc -l inversion2_ff_sco37.full.r2.all.noL.cluster.read4up.txt | cut -d" " -f1`
ls -l inversion2_ff_sco37.full.r2.all.noL.cluster.read4up.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-9/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl inversion2_rr_sco37.full.r2.all.noL.cluster.txt $READ_LEN > inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1
sort -k 10,10nr inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1 > inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1.sort10
sort -k 1,1nr inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1 > inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1.sort1
$RSC/extract2.pl inversion2_rr_sco37.full.r2.all.noL.cluster.txt.1.sort1 0 4 > inversion2_rr_sco37.full.r2.all.noL.cluster.read4up.txt
CNT=`wc -l inversion2_rr_sco37.full.r2.all.noL.cluster.read4up.txt | cut -d" " -f1`
ls -l inversion2_rr_sco37.full.r2.all.noL.cluster.read4up.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-10/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster5.pl inversion2_ff_sco37.full.r2.all.noL.cluster.read4up.txt all.sam.cla.ff.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size $READ_LEN > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt
$RSC/extractCluster5.pl inversion2_rr_sco37.full.r2.all.noL.cluster.read4up.txt all.sam.cla.rr.rmDup.rmMulti2.sco37.mis2.ins51.sort.clu.min2.i2.rmDup.2.size $READ_LEN > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt
CNT=`grep -c "^#####" inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt`
ls -l inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-11/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`grep -c "^#####" inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt`
ls -l inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-12/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster3_1.pl inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt 4 > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4
$RSC/extractCluster3_1.pl inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt 4 > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4


# # realigment to reference genome with BLAST, to check pseudo rearrangement
# mkdir -p tmp_inv/ff
# for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y
# do
#   $RSC/extractCluster3_bwa_chr.pl inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt 4 $i > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4_chr
#   $BLST/blastall -p blastn -d $REF/chromFa/chr$i.fa -e 1e-10 -m 8 -F F < inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4_chr > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0
#   awk -v len=$READ_LEN '$4>=(len*0.95){print}' inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0 > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr
#   $RSC/extractPairEnd_ff_new3_bwa.pl inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr $READ_LEN $MAX_INSERT 1e-2 $READ_LEN > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.ff_chr
# 
#   if [ $i == 1 ]; then
#     cat inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.ff_chr  > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.ff
#   else
#     cat inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.ff_chr >> inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.ff
#   fi
# 
#   mv inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4_chr "tmp_inv/ff""/chr"$i".fa"
#   mv inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr "tmp_inv/ff""/chr"$i".blout"
#   mv inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.ff_chr "tmp_inv/ff""/chr"$i".pair-end.ff"
#  
#   sh $RSC/check_memout.sh $JID 
# done
# 
# mkdir -p tmp_inv/rr
# for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y
# do
#   $RSC/extractCluster3_bwa_chr.pl inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt 4 $i > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4_chr
#   $BLST/blastall -p blastn -d $REF/chromFa/chr$i.fa -e 1e-10 -m 8 -F F < inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4_chr > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0
#   awk -v len=$READ_LEN '$4>=(len*0.95){print}' inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0 > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr
#   $RSC/extractPairEnd_rr_new3_bwa.pl inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr $READ_LEN $MAX_INSERT 1e-2 $READ_LEN > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rr_chr
# 
#   if [ $i == 1 ]; then
#     cat inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rr_chr  > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rr
#   else
#     cat inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rr_chr >> inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rr
#   fi
# 
#   mv inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4_chr "tmp_inv/rr""/chr"$i".fa"
#   mv inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr "tmp_inv/rr""/chr"$i".blout"
#   mv inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rr_chr "tmp_inv/rr""/chr"$i".pair-end.rr"
# 
#   sh $RSC/check_memout.sh $JID
# done


# $RSC/rmPairEnd2_bwa.pl inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.ff inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4 > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1
# $RSC/rmPairEnd2_bwa.pl inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rr inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4 > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1
cp inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4 inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1
cp inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4 inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1

CNT=`grep -c "^#####" inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1`
ls -l inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1 | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-13/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`grep -c "^#####" inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1`
ls -l inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1 | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-14/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1 $READ_LEN > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1
$RSC/chFormat6_bwa.pl inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1 $READ_LEN > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1
sort -k 10,10n inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1 > inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1.sort10
sort -k 10,10n inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1 > inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1.sort10

$RSC/extractCluster5.pl inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1.1 inversion_ff.6 $READ_LEN > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt
$RSC/extractCluster5.pl inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1.1 inversion_rr.6 $READ_LEN > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt
CNT=`grep -c "^#####" inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt`
ls -l inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-15/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`grep -c "^#####" inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt`
ls -l inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-16/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt $READ_LEN > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt
$RSC/chFormat6_bwa.pl inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt $READ_LEN > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt
sort -k 1,1nr inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort1
sort -k 1,1nr inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort1
sort -k 10,10nr inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort10
sort -k 10,10nr inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.txt.sort10

# $RSC/rmNoPrefectMatch_mem_new.pl inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt 1 > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
# $RSC/rmNoPrefectMatch_mem_new.pl inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.cluster.txt 1 > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
  $RSC/rmNoPrefectMatch_mem_new.pl inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1 1 > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
  $RSC/rmNoPrefectMatch_mem_new.pl inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1 1 > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
# for SKIP rmNoPrefectMatch
  cp inversion2_ff_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.ff.e-1 inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
  cp inversion2_rr_sco37.full.r2.all.noL.read4up.cluster.txt.read4.rm_pair-end.rr.e-1 inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt

CNT=`grep -c "^#####" inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt`
ls -l inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-17/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`grep -c "^#####" inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt`
ls -l inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4inv-18/20" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt $READ_LEN > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
$RSC/chFormat6_bwa.pl inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt $READ_LEN > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
sort -k 1,1nr inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
sort -k 1,1nr inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
sort -k 10,10nr inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10
sort -k 10,10nr inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10

$RSC/chFormat3_bwa.pl inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt > inversion2new_ff_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt
$RSC/chFormat3_bwa.pl inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt > inversion2new_rr_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt
$RSC/chkFusionGene2_FF.pl $RSQ inversion2new_ff_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt $READ_LEN > inversion3new_sco37_ff.txt
ls -l inversion3new_sco37_ff.txt | awk -v wd=${WDIR}"_stp4inv-19/20" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG
$RSC/chkFusionGene2_RR.pl $RSQ inversion2new_rr_sco37.r3.noL.e+3.rmMulti.rmNoPrefect.txt $READ_LEN > inversion3new_sco37_rr.txt
ls -l inversion3new_sco37_rr.txt | awk -v wd=${WDIR}"_stp4inv-20/20" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

cp inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new
cp inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new
$RSC/chFormat6_bwa.pl inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new $READ_LEN > inversion2new_ff_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
$RSC/chFormat6_bwa.pl inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new $READ_LEN > inversion2new_rr_sco37.r2.noL.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
