#!/bin/sh
#$ -S /bin/sh
#$ -m ea
#$ -cwd

if [ $# -lt 2 ]; then
  echo "usage: com.rearrangement.4.deletion.pbs [max insert length(bp)] [file.conf] (Log_file)" 1>&2
  exit 1
fi

MAX_INSERT_P200=`expr $1 + 200`
MAX_INSERT=$1
. $2
LOG=$3
JID=void

WDIR=`pwd | rev | cut -d '/' -f1 | rev`

$RSC/chkOverlapCluster_new.pl ../normal/deletion2_sco37.full.r2.txt deletion2_sco37.full.r2.txt  $READ_LEN_N $READ_LEN > deletion2_sco37.full_fr.r2.txt.2
ls -l deletion2_sco37.full_fr.r2.txt.2 | awk -v wd=${WDIR}"_stp4del-1/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/viewClusterRegion.pl deletion2_sco37.full_fr.r2.txt.2 > deletion2_sco37.full_fr.r2.txt.3
$RSC/viewClusterRegion2.pl deletion2_sco37.full_fr.r2.txt.3 $READ_LEN > deletion2_sco37.full_fr.r2.txt.4
$RSC/viewClusterRegion.pl deletion2_sco37.full.r2.txt > deletion2_sco37.full_fr.r2.txt.5
$RSC/viewClusterRegion2.pl deletion2_sco37.full_fr.r2.txt.5 $READ_LEN > deletion2_sco37.full_fr.r2.txt.6
cat deletion2_sco37.full_??.r2.txt.6 > deletion2_sco37.full.r2.all.txt
cat deletion2_sco37.full_??.r2.txt.4 > deletion2_sco37.full.r2.all.noL.txt
CNT=`wc -l deletion2_sco37.full.r2.all.txt | cut -d" " -f1`
ls -l deletion2_sco37.full.r2.all.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-2/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`wc -l deletion2_sco37.full.r2.all.noL.txt | cut -d" " -f1`
ls -l deletion2_sco37.full.r2.all.noL.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-3/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

#---

$RSC/extractNoL_fr.pl ../normal/all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2 deletion2_sco37.full_fr.r2.txt.4 $READ_LEN > deletion2_sco37.full_fr.r2_r1.txt.4
CNT=`wc -l deletion2_sco37.full_fr.r2_r1.txt.4 | cut -d" " -f1`
ls -l deletion2_sco37.full_fr.r2_r1.txt.4 | awk -v c=$CNT -v wd=${WDIR}"_stp4del-4/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster4.pl deletion2_sco37.full_fr.r2_r1.txt.4 all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size $READ_LEN > deletion2_sco37.full.r2.all.noL.cluster.txt
CNT=`grep -c "^#####" deletion2_sco37.full.r2.all.noL.cluster.txt`
ls -l deletion2_sco37.full.r2.all.noL.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-5/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl deletion2_sco37.full.r2.all.noL.cluster.txt $READ_LEN > deletion2_sco37.full.r2.all.noL.cluster.txt.1

sort -k 10,10nr deletion2_sco37.full.r2.all.noL.cluster.txt.1 > deletion2_sco37.full.r2.all.noL.cluster.txt.1.sort10
$RSC/extract2.pl deletion2_sco37.full.r2.all.noL.cluster.txt.1.sort10 9 $MAX_INSERT_P200 > deletion2_sco37.full.r2.all.noL.cluster.insMax.txt
CNT=`wc -l deletion2_sco37.full.r2.all.noL.cluster.insMax.txt  | cut -d" " -f1`
ls -l deletion2_sco37.full.r2.all.noL.cluster.insMax.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-6/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

sort -k 1,1nr deletion2_sco37.full.r2.all.noL.cluster.insMax.txt > deletion2_sco37.full.r2.all.noL.cluster.insMax.txt.sort1
$RSC/extract2.pl deletion2_sco37.full.r2.all.noL.cluster.insMax.txt.sort1 0 4 > deletion2_sco37.full.r2.all.noL.cluster.insMax.read4up.txt
CNT=`wc -l deletion2_sco37.full.r2.all.noL.cluster.insMax.read4up.txt  | cut -d" " -f1`
ls -l deletion2_sco37.full.r2.all.noL.cluster.insMax.read4up.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-7/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster5.pl deletion2_sco37.full.r2.all.noL.cluster.insMax.read4up.txt all.sam.cla.fr_n.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size $READ_LEN > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt
CNT=`grep -c "^#####" deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt`
ls -l deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-8/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster3_1.pl deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt 4 > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4

#---

# # realigment to reference genome with BLAST, to check pseudo rearrangement
# mkdir -p "tmp_del"
# for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y 
# do
#   $RSC/extractCluster3_bwa_chr.pl deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt 4 $i > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4_chr
#   $BLST/blastall -p blastn -d $REF/chromFa/chr$i.fa -e 1e-10 -m 8 -F F < deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4_chr > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0
#   awk -v len=$READ_LEN '$4>=(len*0.95){print}' deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0 > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr  
#   $RSC/extractPairEnd_fr_new3_bwa.pl deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr $READ_LEN $MAX_INSERT 1e-2 $READ_LEN > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.fr.new3_chr
#
#   if [ $i == 1 ]; then
#     cat deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.fr.new3_chr  > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.fr.new3
#   else 
#     cat deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.fr.new3_chr >> deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.fr.new3
#   fi  
#
#   mv deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4_chr "tmp_del""/chr"$i".fa"
#   mv deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr "tmp_del""/chr"$i".blout"
#
#   sh $RSC/check_memout.sh $JID 
# done

#---

# $RSC/rmPairEnd2_bwa.pl deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.fr.new3 deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4 > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1
cp deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4 deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1

CNT=`grep -c "^#####" deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4`
ls -l deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4 | awk -v c=$CNT -v wd=${WDIR}"_stp4del-9/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`grep -c "^#####" deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1`
ls -l deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1 | awk -v c=$CNT -v wd=${WDIR}"_stp4del-10/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1 $READ_LEN > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1
sort -k 10,10n deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1 > deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1.sort10

$RSC/extractCluster5.pl deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1.1 deletion_fr.6 $READ_LEN > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.cluster.txt
CNT=`grep -c "^#####" deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.cluster.txt`
ls -l deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-11/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.cluster.txt $READ_LEN > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt
sort -k 1,1nr deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt.sort1
sort -k 10,10nr deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.txt.sort10

# $RSC/rmNoPrefectMatch_mem_new.pl deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.cluster.txt                    1 > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt

  $RSC/rmNoPrefectMatch_mem_new.pl deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1 1 > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt
  # for SKIP rmNoPrefectMatch
  cp deletion2_sco37.full.r2.all.noL.insMax.read4up.cluster.txt.read4.rm_pair-end.fr.e-1 deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt

CNT=`grep -c "^#####" deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt`
ls -l deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4del-12/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt $READ_LEN > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
sort -k 1,1nr deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
sort -k 10,10nr deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10

$RSC/chFormat3_bwa.pl deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt > deletion2new_sco37.r3.noL.insMax.e+3.rmMulti.rmNoPrefect.txt
$RSC/chkFusionGene2_FR.pl $RSQ deletion2new_sco37.r3.noL.insMax.e+3.rmMulti.rmNoPrefect.txt $READ_LEN > deletion3new_sco37.txt
$RSC/chFormat2_FR.pl deletion3new_sco37.txt $READ_LEN > deletion3new_1.txt
ls -l deletion3new_1.txt | awk -v wd=${WDIR}"_stp4del-13/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat4.pl deletion3new_1.txt > deletion3new_circos.txt
cp deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new
$RSC/chFormat6_bwa.pl deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new $READ_LEN > deletion2new_sco37.r2.noL.insMax.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
