#!/bin/sh
#$ -S /bin/sh
#$ -m ea
#$ -cwd

if [ $# -lt 2 ]; then
  echo "usage: com.rearrangement.4.tandem.pbs [max insert length(bp)] [file.conf] (Log_file)" 1>&2
  exit 1
fi

MAX_INSERT=$1
. $2
LOG=$3
JID=void

WDIR=`pwd | rev | cut -d '/' -f1 | rev`


$RSC/chkOverlapCluster_new.pl ../normal/tandem_duplication2_sco37.full_rf.r2.txt tandem_duplication2_sco37.full_rf.r2.txt $READ_LEN_N $READ_LEN > tandem_duplication2_sco37.full_rf.r2.txt.2
ls -l tandem_duplication2_sco37.full_rf.r2.txt.2 | awk -v wd=${WDIR}"_stp4tdm-1/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

$RSC/viewClusterRegion.pl tandem_duplication2_sco37.full_rf.r2.txt.2 > tandem_duplication2_sco37.full_rf.r2.txt.3
$RSC/viewClusterRegion2.pl tandem_duplication2_sco37.full_rf.r2.txt.3 $READ_LEN > tandem_duplication2_sco37.full_rf.r2.txt.4
$RSC/viewClusterRegion.pl tandem_duplication2_sco37.full_rf.r2.txt > tandem_duplication2_sco37.full_rf.r2.txt.5
$RSC/viewClusterRegion2.pl tandem_duplication2_sco37.full_rf.r2.txt.5 $READ_LEN > tandem_duplication2_sco37.full_rf.r2.txt.6
cat tandem_duplication2_sco37.full_rf.r2.txt.6 > tandem_duplication2_sco37.full.r2.all.txt
cat tandem_duplication2_sco37.full_rf.r2.txt.4 > tandem_duplication2_sco37.full.r2.all.noL.txt
CNT=`wc -l tandem_duplication2_sco37.full.r2.all.txt | cut -d" " -f1`
ls -l tandem_duplication2_sco37.full.r2.all.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-2/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`wc -l tandem_duplication2_sco37.full.r2.all.noL.txt | cut -d" " -f1`
ls -l tandem_duplication2_sco37.full.r2.all.noL.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-3/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractNoL_rf.pl ../normal/all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2 tandem_duplication2_sco37.full_rf.r2.txt.4 $READ_LEN > tandem_duplication2_sco37.full_rf.r2_r1.txt.4
CNT=`wc -l tandem_duplication2_sco37.full_rf.r2_r1.txt.4 | cut -d" " -f1`
ls -l tandem_duplication2_sco37.full_rf.r2_r1.txt.4 | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-4/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster4.pl tandem_duplication2_sco37.full_rf.r2_r1.txt.4 all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size $READ_LEN > tandem_duplication2_sco37.full.r2.all.noL.cluster.txt
CNT=`grep -c "^#####" tandem_duplication2_sco37.full.r2.all.noL.cluster.txt`
ls -l tandem_duplication2_sco37.full.r2.all.noL.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-5/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl tandem_duplication2_sco37.full.r2.all.noL.cluster.txt $READ_LEN > tandem_duplication2_sco37.full.r2.all.noL.cluster.txt.1
sort -k 10,10nr tandem_duplication2_sco37.full.r2.all.noL.cluster.txt.1 > tandem_duplication2_sco37.full.r2.all.noL.cluster.txt.1.sort10
$RSC/extract2.pl tandem_duplication2_sco37.full.r2.all.noL.cluster.txt.1.sort10 9 100 > tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt
CNT=`wc -l tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt | cut -d" " -f1`
ls -l tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-6/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

sort -k 1,1nr tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt > tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt.sort1
$RSC/extract2.pl tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.txt.sort1 0 4 > tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.read4up.txt
CNT=`wc -l tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.read4up.txt | cut -d" " -f1`
ls -l tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.read4up.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-7/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster5.pl tandem_duplication2_sco37.full.r2.all.noL.cluster.ins100up.read4up.txt all.sam.cla.rf.rmDup.rmMulti2.sco37.mis2.sort.clu.min2.2.size $READ_LEN > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt
CNT=`grep -c "^#####" tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt`
ls -l tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-8/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/extractCluster3_1.pl tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt 4 > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4


# # realigment to reference genome with BLAST, to check pseudo rearrangement
# mkdir "tmp_tdm"
# for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y 
# do
#   $RSC/extractCluster3_bwa_chr.pl tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt 4 $i > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4_chr
#   $BLST/blastall -p blastn -d $REF/chromFa/chr$i.fa -e 1e-10 -m 8 -F F < tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4_chr > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0
#   awk -v len=$READ_LEN '$4>=(len*0.95){print}' tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr_0 > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr
#   $RSC/extractPairEnd_rf_new3_bwa.pl tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr $READ_LEN $MAX_INSERT 1e-2 $READ_LEN > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rf.new3_chr
# 
#   if [ $i == 1 ]; then
#     cat tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rf.new3_chr  > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rf.new3
#   else 
#     cat tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rf.new3_chr >> tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rf.new3
#   fi  
# 
#  mv tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4_chr "tmp_tdm""/chr"$i".fa"
#  mv tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8_chr "tmp_tdm""/chr"$i".blout"
#  
#  sh $RSC/check_memout.sh $JID
# done

# $RSC/rmPairEnd2_bwa.pl tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.seq4.blastn.e-1.ff.m8.pair-end.rf.new3 tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4 > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1
cp tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4 tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1

CNT=`grep -c "^#####" tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4`
ls -l tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4 | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-9/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG
CNT=`grep -c "^#####" tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1`
ls -l tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1 | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-10/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1 $READ_LEN > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1.1
sort -k 10,10n tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1.1 > tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1.1.sort10
$RSC/extractCluster5.pl tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1.1 tandem_rf.6 $READ_LEN > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.cluster.txt
CNT=`grep -c "^#####" tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.cluster.txt`
ls -l tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-11/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.cluster.txt $READ_LEN > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt
sort -k 1,1nr tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt.sort1
sort -k 10,10nr tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.txt.sort10

# $RSC/rmNoPrefectMatch_mem_new.pl tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.cluster.txt 1 > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt
  $RSC/rmNoPrefectMatch_mem_new.pl tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1 1 > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt
# for SKIP rmNoPrefectMatch
  cp tandem_duplication2_sco37.full.r2.all.noL.ins100up.read4up.cluster.txt.read4.rm_pair-end.rf.e-1 tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt

CNT=`grep -c "^#####" tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt`
ls -l tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt | awk -v c=$CNT -v wd=${WDIR}"_stp4tdm-12/13" '{print "log: "wd"\t"$10" [\t"c" cluster,\tfilesize =\t"$5" ] generated"}' >> $LOG

$RSC/chFormat6_bwa.pl tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt $READ_LEN > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt
sort -k 1,1nr tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort1
sort -k 10,10nr tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.sort10

$RSC/chFormat3_bwa.pl tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt > tandem_duplication2new_sco37.r3.noL.ins100up.e+3.rmMulti.rmNoPrefect.txt
$RSC/chkFusionGene2_RF.pl $RSQ tandem_duplication2new_sco37.r3.noL.ins100up.e+3.rmMulti.rmNoPrefect.txt $READ_LEN > tandem_duplication3new_sco37.txt
ls -l tandem_duplication3new_sco37.txt | awk -v wd=${WDIR}"_stp4tdm-13/13" '{print "log: "wd"\t"$10" [ filesize =\t"$5" ] generated"}' >> $LOG

cp tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch,cluster.txt tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new
$RSC/chFormat6_bwa.pl tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.cluster.txt.new $READ_LEN > tandem_duplication2new_sco37.r2.noL.ins100up.read4up.e+3.rmMulti.rmNoPrefectMatch.txt.new
